import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { schemaContract, schemaDigest } from "./release/schema.mjs";

export function prepareRelease() {
  const config = JSON.parse(readFileSync("appwrite.config.json", "utf8"));
  const contract = schemaContract(config);
  const files = execFileSync("git", ["ls-files", "--cached", "--others", "--exclude-standard", "-z"], { encoding: "utf8" }).split("\0").filter(Boolean)
    .filter(p => /^(app\/|lib\/|functions\/mio-sms\/src\/|scripts\/|packages\/|apps\/mobile\/|appwrite.config.json$|package.json$|pnpm-|next.config|tsconfig|postcss|eslint)/.test(p))
    .filter(p => !/\/(dist|ios|android|node_modules|\.expo)\//.test(p))
    .filter(p => !p.endsWith("release.generated.ts") && !p.endsWith("generated.ts") && p !== "lib/generated/appwrite.ts").sort();
  const hash = createHash("sha256");
  for (const file of files) { hash.update(file); hash.update("\0"); hash.update(readFileSync(file)); hash.update("\0"); }
  const commit = execFileSync("git", ["rev-parse", "HEAD"], { encoding: "utf8" }).trim();
  const release = { releaseId: `${commit.slice(0, 12)}-${hash.digest("hex").slice(0, 20)}`, commit, schemaVersion: contract.version, schemaDigest: schemaDigest(contract) };
  writeFileSync("functions/mio-sms/src/release.generated.ts", `// Generated by scripts/prepare-release.mjs. Never contains environment values.\nexport const release = ${JSON.stringify(release, null, 2)};\nexport const contract = ${JSON.stringify(contract, null, 2)};\n`);
  return { ...release, contract };
}
if (process.argv[1]?.endsWith("prepare-release.mjs")) console.log(`Prepared release ${prepareRelease().releaseId}`);
