import type { Models } from 'appwrite';

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types functions/mio-sms/src/generated.ts --language ts`.

export type Notes = Models.Row & {
    ownerId: string;
    title: string;
    body: string;
    archived: boolean;
    source: string;
}

export type Attachments = Models.Row & {
    ownerId: string;
    noteId: string;
    fileId: string;
    name: string;
    size: number;
    mimeType: string;
}

export type SmsConnections = Models.Row & {
    ownerId: string;
    phone: string;
    targetId: string;
}

export type SmsChallenges = Models.Row & {
    tokenHash: string;
    expiresAt: string;
}

export type SmsReceipts = Models.Row & {
    ownerId: string;
    phone: string;
    targetId: string;
    payloadHash: string;
    reply: string;
    replyQueued: boolean;
}
