import type { Models } from 'appwrite';

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types functions/mio-sms/src/generated.ts --language ts`.

export type Notes = Models.Row & {
    ownerId: string;
    title: string;
    body: string;
    archived: boolean;
    source: string;
    completed: boolean;
    project: string;
}

export type Attachments = Models.Row & {
    ownerId: string;
    noteId: string;
    fileId: string;
    name: string;
    size: number;
    mimeType: string;
}

export type SmsConnections = Models.Row & {
    ownerId: string;
    phone: string;
    targetId: string;
}

export type SmsChallenges = Models.Row & {
    tokenHash: string;
    expiresAt: string;
}

export type SmsReceipts = Models.Row & {
    ownerId: string;
    phone: string;
    targetId: string;
    payloadHash: string;
    reply: string;
    replyQueued: boolean;
    reminderIds: string[];
    deliveryMode: string;
}

export type SmsJobs = Models.Row & {
    ownerId: string;
    phone: string;
    targetId: string;
    payloadHash: string;
    body: string;
    status: string;
    attempts: number;
    nextAttemptAt: string;
}

export type SmsConversations = Models.Row & {
    ownerId: string;
    timezone: string;
    defaultOffsetMinutes: number;
    leaseToken: string;
    leaseUntil: string;
}

export type SmsTurns = Models.Row & {
    ownerId: string;
    userText: string;
    reply: string;
    noteIds: string[];
    reminderIds: string[];
}

export type Reminders = Models.Row & {
    ownerId: string;
    noteId: string;
    eventAt: string;
    remindAt: string;
    timezone: string;
    message: string;
    status: string;
    revision: number;
    messageId: string;
    appliedMessageId: string;
    targetId: string;
    syncPending: boolean;
    lastError: string;
}
